#!/usr/bin/python3
"""
ESTE MODULO DEFINE UNA CALSE CUADRADA VACIA QUE REPRESENTA UN CUADRADO :D.
"""


class Square:
    """
    ESTO REPRESENTA UNA CLASE CUADRADA
    UN CUADADO SIN ATRIBUTOS NI METODOS DEFINIDOS
    """
    pass
